export const DEFAULT_AGENT_K9_DEVELOPMENT_WALLET =
  "Cdij4T6EXdz1MFGChuqBNo7kZ8E5unTSLyeP8SGvazZ4";

export const AGENT_K9_DEVELOPMENT_WALLET =
  process.env.NEXT_PUBLIC_AGENT_K9_DEVELOPMENT_WALLET ||
  process.env.NEXT_PUBLIC_LEVI_DEVELOPMENT_WALLET ||
  DEFAULT_AGENT_K9_DEVELOPMENT_WALLET;
