// /* eslint-disable import/no-default-export */
// import type { NextPage } from 'next';
// import dynamic from 'next/dynamic';
// import { LoadingIndicator } from '../components/LoadingIndicator';

// export const LiFiWidgetNext = dynamic(
//   () => import('../components/Widget').then((module) => module.Widget) as any,
//   {
//     ssr: false,
//     loading: () => <LoadingIndicator />,
//   },
// );

// const Home: NextPage = () => {
//   return <LiFiWidgetNext />;
// };

// export default Home;

/* eslint-disable import/no-default-export */
// import type { NextPage } from 'next';
// import dynamic from 'next/dynamic';
// import { LoadingIndicator } from '../components/LoadingIndicator';
// import React, { useEffect, useRef, useState } from 'react';
// import Head from "next/head";
// import Header from "../components/header";
// import Navbar from "../components/Navbar";
// import CTAComponent from "../components/CTAComponent";
// import Discover from "../components/Discover";
// import Welcome from "../components/Welcome";
// import Main from "../components/main";
// import TokenGrid from "../components/TokenGrid";
// import PriceLineChart from '../components/PriceLineChart';

// export const LiFiWidgetNext = dynamic(
//   () => import('../components/Widget').then((module) => module.Widget) as any,
//   {
//     ssr: false,
//     loading: () => <LoadingIndicator />,
//   },
// );

// const Home: NextPage = () => {
//   const sectionRef = useRef<HTMLDivElement>(null);

//   const [isVisible, setIsVisible] = useState(false);
//   const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

//   useEffect(() => {
//     const handleScroll = () => {
//       if (sectionRef.current) {
//         const topPosition = sectionRef.current.getBoundingClientRect().top;
//         const isVisible = topPosition < window.innerHeight - 100;
//         setIsVisible(isVisible);
//       }
//     };


//     window.addEventListener('scroll', handleScroll);
//     handleScroll();
//     return () => {
//       window.removeEventListener('scroll', handleScroll);
//     };
//   }, []);

//   return (
//     <section
//       ref={sectionRef}
//       className={`w-full h-full gradient-bg-welcome fade-in-scroll${isVisible ? ' visible' : ''}`}
//     >
//       <Head>
//         <title>FlowFinance</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <header>
//         <Navbar />
//         <Header />
//       </header>
//       <main>
//         <Welcome />
//         <Discover />
//         <CTAComponent />
//         <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
//         {selectedPoolAddress && <PriceLineChart poolAddresses={selectedPoolAddress} />}
//         <Main />
//         <div className="w-full max-w-screen-sm mx-auto overflow-hidden">
//   <div className="transform scale-75 sm:scale-100"
//     style={{ transformOrigin: '' }}>
//     <LiFiWidgetNext />
//   </div>
// </div>


//       </main>
//     </section>
//   );
// };

// export default Home;




// import { NextPage } from 'next';
// import dynamic from 'next/dynamic';
// import { LoadingIndicator } from '../components/LoadingIndicator';
// import React, { useEffect, useRef, useState } from 'react';
// import Head from "next/head";
// import Header from "../components/header";
// import Navbar from "../components/Navbar";
// import CTAComponent from "../components/CTAComponent";
// import Discover from "../components/Discover";
// import Welcome from "../components/Welcome";
// import Main from "../components/main";
// import TokenGrid from "../components/TokenGrid";
// import PriceLineChart from '../components/PriceLineChart';
// import { QueryClient, QueryClientProvider } from 'react-query';

// const queryClient = new QueryClient();

// const LiFiWidgetNext = dynamic(
//   () => import('../components/Widget').then((module) => module.Widget) as any,
//   {
//     ssr: false,
//     loading: () => <LoadingIndicator />,
//   },
// );

// const Home: NextPage = () => {
//   const sectionRef = useRef<HTMLDivElement>(null);

//   const [isVisible, setIsVisible] = useState(false);
//   const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

//   useEffect(() => {
//     const handleScroll = () => {
//       if (sectionRef.current) {
//         const topPosition = sectionRef.current.getBoundingClientRect().top;
//         const isVisible = topPosition < window.innerHeight - 100;
//         setIsVisible(isVisible);
//       }
//     };

//     window.addEventListener('scroll', handleScroll);
//     handleScroll();
//     return () => {
//       window.removeEventListener('scroll', handleScroll);
//     };
//   }, []);

//   return (
//     <QueryClientProvider client={queryClient}>


//       <section
//         ref={sectionRef}
//         className={`w-full h-full gradient-bg-welcome fade-in-scroll${isVisible ? ' visible' : ''}`}
//       >
//         <div className="w-full max-w-screen-sm mx-auto overflow-hidden">
//             <div className="transform scale-75 sm:scale-100" style={{ transformOrigin: 'center' }}>

//         <Head>
//           <title>FlowFinance</title>
//           <meta name="description" content="Generated by create next app" />
//           <link rel="icon" href="/favicon.ico" />
//         </Head>
//         <header>
//           <Navbar />
//           <Header />
//         </header>
//         <main>
//           <Welcome />
//           <Discover />
//           <CTAComponent />
//           <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
//           {selectedPoolAddress && <PriceLineChart poolAddresses={selectedPoolAddress} />}
//           <Main />
//          <LiFiWidgetNext />

//         </main>
//         </div>
//           </div>
//       </section>

//     </QueryClientProvider>
//   );
// };

// export default Home;


// import { NextPage } from 'next';
// import dynamic from 'next/dynamic';
// import { LoadingIndicator } from '../components/LoadingIndicator';
// import React, { useEffect, useRef, useState } from 'react';
// import Head from "next/head";
// import Header from "../components/header";
// import Navbar from "../components/Navbar";
// import CTAComponent from "../components/CTAComponent";
// import Discover from "../components/Discover";
// import Welcome from "../components/Welcome";
// import Main from "../components/main";
// import TokenGrid from "../components/TokenGrid";
// import PriceLineChart from '../components/PriceLineChart';
// import { QueryClient, QueryClientProvider } from 'react-query';

// const queryClient = new QueryClient();

// const LiFiWidgetNext = dynamic(
//   () => import('../components/Widget').then((module) => module.Widget) as any,
//   {
//     ssr: false,
//     loading: () => <LoadingIndicator />,
//   },
// );

// const Home: NextPage = () => {
//   const sectionRef = useRef<HTMLDivElement>(null);

//   const [isVisible, setIsVisible] = useState(false);
//   const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

//   useEffect(() => {
//     const handleScroll = () => {
//       if (sectionRef.current) {
//         const topPosition = sectionRef.current.getBoundingClientRect().top;
//         const bottomPosition = sectionRef.current.getBoundingClientRect().bottom;
//         const isVisible = topPosition < window.innerHeight && bottomPosition > 0;
//         setIsVisible(isVisible);
//       }
//     };

//     window.addEventListener('scroll', handleScroll);
//     handleScroll();
//     return () => {
//       window.removeEventListener('scroll', handleScroll);
//     };
//   }, []);

//   return (
//     <QueryClientProvider client={queryClient}>
//       <section
//         ref={sectionRef}
//         className={`w-full h-full gradient-bg-welcome fade-in-scroll${isVisible ? ' visible' : ''}`}
//       >
//         <div className="w-full h-full max-w-screen-sm  overflow-hidden">
//           <div className="transform scale-75 sm:scale-100" style={{ transformOrigin: 'center' }}>
//             <Head>
//               <title>FlowFinance</title>
//               <meta name="description" content="Generated by create next app" />
//               <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <header>
//               <Navbar />
//               <Header />
//             </header>
//             <main>
//               <Welcome />
//               <Discover />
//               <CTAComponent />
//               <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
//               {selectedPoolAddress && <PriceLineChart poolAddresses={selectedPoolAddress} />}
//               <Main />
//               <LiFiWidgetNext />
//             </main>
//           </div>
//         </div>
//       </section>
//     </QueryClientProvider>
//   );
// };

// export default Home;





// import { NextPage } from 'next';
// import dynamic from 'next/dynamic';
// import { LoadingIndicator } from '../components/LoadingIndicator';
// import React, { useEffect, useRef, useState } from 'react';
// import Head from "next/head";
// import Header from "../components/header";
// import Navbar from "../components/Navbar";
// import CTAComponent from "../components/CTAComponent";
// import Discover from "../components/Discover";
// import Welcome from "../components/Welcome";
// import Main from "../components/main";
// import TokenGrid from "../components/TokenGrid";
// import PriceLineChart from '../components/PriceLineChart';
// import { QueryClient, QueryClientProvider } from 'react-query';
// import Link from 'next/link';

// const queryClient = new QueryClient();

// const LiFiWidgetNext = dynamic(
//   () => import('../components/Widget').then((module) => module.Widget) as any,
//   {
//     ssr: false,
//     loading: () => <LoadingIndicator />,
//   },
// );

// const Home: NextPage = () => {
//   const sectionRef = useRef<HTMLDivElement>(null);

//   const [isVisible, setIsVisible] = useState(false);
//   const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

//   useEffect(() => {
//     const handleScroll = () => {
//       if (sectionRef.current) {
//         const topPosition = sectionRef.current.getBoundingClientRect().top;
//         const bottomPosition = sectionRef.current.getBoundingClientRect().bottom;
//         const isVisible = topPosition < window.innerHeight && bottomPosition > 0;
//         setIsVisible(isVisible);
//       }
//     };

//     window.addEventListener('scroll', handleScroll);
//     handleScroll();
//     return () => {
//       window.removeEventListener('scroll', handleScroll);
//     };
//   }, []);

//   return (
//     <QueryClientProvider client={queryClient}>
//       <section
//         ref={sectionRef}
//         className={`w-full h-full gradient-bg-welcome fade-in-scroll${isVisible ? ' visible' : ''}`}
//       >
//         <div className="w-full max-w-screen-sm mx-auto overflow-hidden">
//           <div className="transform scale-75 sm:scale-100" style={{ transformOrigin: 'top' }}>
//             <Head>
//               <title>FlowFinance</title>
//               <meta name="description" content="Generated by create next app" />
//               <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <header>
//               <Navbar />
//               <Header />
//             </header>
//             <main>
//               <Welcome />
//               <Discover />
//               <CTAComponent />
//               <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
//               {selectedPoolAddress && <PriceLineChart poolAddresses={selectedPoolAddress} />}
//               <Main />
//               <LiFiWidgetNext />


//             </main>
//           </div>
//         </div>
//       </section>
//     </QueryClientProvider>
//   );
// };

// export default Home;







// import { NextPage } from 'next';
// import dynamic from 'next/dynamic';
// import { LoadingIndicator } from '../components/LoadingIndicator';
// import React, { useEffect, useRef, useState } from 'react';
// import Head from "next/head";
// import Header from "../components/header";
// import Navbar from "../components/Navbar";
// import CTAComponent from "../components/CTAComponent";
// import Discover from "../components/Discover";
// import Welcome from "../components/Welcome";
// import Main from "../components/main";
// import TokenGrid from "../components/TokenGrid";
// import PriceLineChart from '../components/PriceLineChart';
// import { QueryClient, QueryClientProvider } from 'react-query';
// import Link from 'next/link';

// const queryClient = new QueryClient();

// const LiFiWidgetNext = dynamic(
//   () => import('../components/Widget').then((module) => module.Widget) as any,
//   {
//     ssr: false,
//     loading: () => <LoadingIndicator />,
//   },
// );

// const Home: NextPage = () => {
//   const sectionRef = useRef<HTMLDivElement>(null);

//   const [isVisible, setIsVisible] = useState(false);
//   const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

//   useEffect(() => {
//     const handleScroll = () => {
//       if (sectionRef.current) {
//         const topPosition = sectionRef.current.getBoundingClientRect().top;
//         const bottomPosition = sectionRef.current.getBoundingClientRect().bottom;
//         const isVisible = topPosition < window.innerHeight && bottomPosition > 0;
//         setIsVisible(isVisible);
//       }
//     };

//     window.addEventListener('scroll', handleScroll);
//     handleScroll();
//     return () => {
//       window.removeEventListener('scroll', handleScroll);
//     };
//   }, []);

//   return (
//     <QueryClientProvider client={queryClient}>
//       <section
//         ref={sectionRef}
//         className={`w-full h-full gradient-bg-welcome fade-in-scroll${isVisible ? ' visible' : ''}`}
//       >
//         <div className="w-full h-full max-w-screen-sm  overflow-hidden">
//           <div className="transform scale-75 sm:scale-100" style={{ transformOrigin: 'top' }}>
//             <Head>
//               <title>FlowFinance</title>
//               <meta name="description" content="Generated by create next app" />
//               <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <header>
//               <Navbar />
//               <Header />
//             </header>
//             <main>
//               <Welcome />
//               <Discover />
//               <CTAComponent />
//               <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
//               {selectedPoolAddress && <PriceLineChart poolAddresses={selectedPoolAddress} />}
//               <Main />

//               <LiFiWidgetNext />
//             </main>
//           </div>
//         </div>
//       </section>
//     </QueryClientProvider>
//   );
// };

// export default Home;










// ANDRUCHOOOOOOOOOOOOOO









// import { NextPage } from 'next';
// import dynamic from 'next/dynamic';
// import { LoadingIndicator } from '../components/LoadingIndicator';
// import React, { useEffect, useRef, useState } from 'react';
// import Head from "next/head";
// import Header from "../components/header";
// import Navbar from "../components/Navbar";
// import CTAComponent from "../components/CTAComponent";
// import Discover from "../components/Discover";
// import Welcome from "../components/Welcome";
// import Main from "../components/main";
// import TokenGrid from "../components/TokenGrid";
// import PriceLineChart from '../components/PriceLineChart';
// import { QueryClient, QueryClientProvider } from 'react-query';

// const queryClient = new QueryClient();

// const LiFiWidgetNext = dynamic(
//   () => import('../components/Widget').then((module) => module.Widget) as any,
//   {
//     ssr: false,
//     loading: () => <LoadingIndicator />,
//   },
// );

// const Home: NextPage = () => {
//   const sectionRef = useRef<HTMLDivElement>(null);

//   const [isVisible, setIsVisible] = useState(false);
//   const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

//   useEffect(() => {
//     const handleScroll = () => {
//       if (sectionRef.current) {
//         const topPosition = sectionRef.current.getBoundingClientRect().top;
//         const bottomPosition = sectionRef.current.getBoundingClientRect().bottom;
//         const isVisible = topPosition < window.innerHeight && bottomPosition > 0;
//         setIsVisible(isVisible);
//       }
//     };

//     window.addEventListener('scroll', handleScroll);
//     handleScroll();
//     return () => {
//       window.removeEventListener('scroll', handleScroll);
//     };
//   }, []);

//   return (
//     <QueryClientProvider client={queryClient}>
//       <section
//         ref={sectionRef}
//         className={`w-full h-full gradient-bg-welcome fade-in-scroll${isVisible ? ' visible' : ''}`}
//       >
//         <div className="w-full h-full max-w-screen-sm">
//           <div className="transform scale-75 sm:scale-100" style={{ transformOrigin: 'top' }}>
//             <Head>
//               <title>FlowFinance</title>
//               <meta name="description" content="Generated by create next app" />
//               <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <header>
//               <Navbar />
//               <Header />
//             </header>
//             <main>
//               <Welcome />
//               <Discover />
//               <CTAComponent />
//               <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
//               {selectedPoolAddress && <PriceLineChart poolAddresses={selectedPoolAddress} />}
//               <LiFiWidgetNext />
//               <Main />

//             </main>
//           </div>
//         </div>
//       </section>
//     </QueryClientProvider>
//   );
// };

// export default Home;


// import { NextPage } from 'next';
// import dynamic from 'next/dynamic';
// import { LoadingIndicator } from '../components/LoadingIndicator';
// import React, { useEffect, useRef, useState } from 'react';
// import Head from "next/head";
// import Header from "../components/header";
// import Navbar from "../components/Navbar";
// import CTAComponent from "../components/CTAComponent";
// import Discover from "../components/Discover";
// import Welcome from "../components/Welcome";
// import Main from "../components/main";
// import TokenGrid from "../components/TokenGrid";
// import PriceLineChart from '../components/PriceLineChart';
// import { QueryClient, QueryClientProvider } from 'react-query';

// const queryClient = new QueryClient();

// const LiFiWidgetNext = dynamic(
//   () => import('../components/Widget').then((module) => module.Widget) as any,
//   {
//     ssr: false,
//     loading: () => <LoadingIndicator />,
//   },
// );

// const Home: NextPage = () => {
//   const sectionRef = useRef<HTMLDivElement>(null);

//   const [isVisible, setIsVisible] = useState(false);
//   const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

//   useEffect(() => {
//     const handleScroll = () => {
//       if (sectionRef.current) {
//         const topPosition = sectionRef.current.getBoundingClientRect().top;
//         const bottomPosition = sectionRef.current.getBoundingClientRect().bottom;
//         const isVisible = topPosition < window.innerHeight && bottomPosition > 0;
//         setIsVisible(isVisible);
//       }
//     };

//     const handleResize = () => {
//       handleScroll();
//     };

//     window.addEventListener('scroll', handleScroll);
//     window.addEventListener('resize', handleResize);

//     handleScroll();

//     return () => {
//       window.removeEventListener('scroll', handleScroll);
//       window.removeEventListener('resize', handleResize);
//     };
//   }, []);

//   return (
//     <QueryClientProvider client={queryClient}>
//       <section
//         ref={sectionRef}
//         className={`w-full h-full gradient-bg-welcome fade-in-scroll${isVisible ? ' visible' : ''}`}
//       >
//         <div className="w-full h-full max-w-screen-sm flex flex-col justify-between">
//           <div className="transform scale-75 sm:scale-100" style={{ transformOrigin: '' }}>
//             <Head>
//               <title>FlowFinance</title>
//               <meta name="description" content="Generated by create next app" />
//               <link rel="icon" href="/favicon.ico" />
//             </Head>
//             <header>
//               <Navbar />
//               <Header />
//             </header>
//             <main>
//               <Welcome />
//               <Discover />
//               <CTAComponent />
//               <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
//               {selectedPoolAddress && <PriceLineChart poolAddresses={selectedPoolAddress} />}
//               <Main />
//             </main>
//           </div>
//           <div className="mt-10">
//             <div className="transform scale-75 sm:scale-100" style={{ transformOrigin: 'bottom' }}>
//               <LiFiWidgetNext />
//             </div>
//           </div>
//         </div>
//       </section>
//     </QueryClientProvider>
//   );
// };

// export default Home;





// import React, { useEffect, useRef, useState } from 'react';
// import Head from "next/head";
// import Header from "../components/header";
// import Navbar from "../components/Navbar";
// import CTAComponent from "../components/CTAComponent";
// import Discover from "../components/Discover";
// import Welcome from "../components/Welcome";
// import Main from "../components/main";
// import TokenGrid from "../components/TokenGrid";
// import PriceLineChart from '../components/PriceLineChart';

// export default function Home() {
//   const sectionRef = useRef(null);
//   const [isVisible, setIsVisible] = useState(false);
//   const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

//   useEffect(() => {
//     const handleScroll = () => {
//       const topPosition = sectionRef.current!.getBoundingClientRect().top;
//       const isVisible = topPosition < window.innerHeight - 100;
//       setIsVisible(isVisible);
//     };

//     window.addEventListener('scroll', handleScroll);
//     handleScroll();
//     return () => {
//       window.removeEventListener('scroll', handleScroll);
//     };
//   }, []);

//   return (
//     <section
//       ref={sectionRef}
//       className={`w-full h-full gradient-bg-welcome fade-in-scroll${isVisible ? ' visible' : ''}`}
//     >

//       <Head>
//         <title>FlowFinance</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <header>
//         <Navbar />

//       </header>
//       <main>
//         <Welcome />
//         <Discover />
//         <CTAComponent />
//         <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
//         {selectedPoolAddress && <PriceLineChart poolAddresses={selectedPoolAddress} />}
//         <Main />
//       </main>
//     </section>
//   );
// }


// import React, { useEffect, useRef, useState } from 'react';
// import Head from "next/head";
// import Navbar from "../components/Navbar";
// import CTAComponent from "../components/CTAComponent";
// import Discover from "../components/Discover";
// import Welcome from "../components/Welcome";
// import Main from "../components/main";
// import TokenGrid from "../components/TokenGrid";
// import mySVGBackground from '../public/FONDOFF.svg'; // Importa la ruta de tu archivo SVG



// export default function Home() {
//   const sectionRef = useRef<HTMLDivElement>(null);
//   const [isVisible, setIsVisible] = useState(false);
//   const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

//   useEffect(() => {
//     const handleScroll = () => {
//       if(sectionRef.current) {
//         const topPosition = sectionRef.current.getBoundingClientRect().top;
//         const isVisible = topPosition < window.innerHeight - 100;
//         setIsVisible(isVisible);
//       }
//     };

//     window.addEventListener('scroll', handleScroll);
//     handleScroll();
//     return () => {
//       window.removeEventListener('scroll', handleScroll);
//     };
//   }, []);

//   return (
//     <section
//       ref={sectionRef}
//       className={`w-full h-full  fade-in-scroll${isVisible ? ' visible' : ''}`}

//     >
//       <Head>
//         <title>FlowFinance</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <header>
//         <Navbar />
//       </header>
//       <main>
//         <Welcome />
//         <Discover />
//         <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
//         <CTAComponent />
//         {/* {selectedPoolAddress && <PriceLineChart poolAddresses={selectedPoolAddress} />} */}
//         {/* <Main /> */}
//       </main>
//     </section>
//   );
// }




// import React, { useEffect, useRef, useState } from 'react';
// import Head from 'next/head';
// import Navbar from '../components/Navbar';
// import CTAComponent from '../components/CTAComponent';
// import Welcome from '../components/Welcome';
// import TokenGrid from '../components/TokenGrid';


// export default function Home() {
//   const sectionRef = useRef<HTMLDivElement>(null);
//   const [isVisible, setIsVisible] = useState(false);
//   const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

//   useEffect(() => {
//     const handleScroll = () => {
//       if (sectionRef.current) {
//         const topPosition = sectionRef.current.getBoundingClientRect().top;
//         const isVisible = topPosition < window.innerHeight - 100;
//         setIsVisible(isVisible);
//       }
//     };

//     window.addEventListener('scroll', handleScroll);
//     handleScroll();
//     return () => {
//       window.removeEventListener('scroll', handleScroll);
//     };
//   }, []);

//   return (
//     <section
//   ref={sectionRef}
//   className={`w-full gradient-bg-welcome min-h-screen fade-in-scroll${isVisible ? ' visible' : ''} bg-cover bg-center`}
// >      
//         <Head>
//         <title>FlowFinance</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//        </Head>
//       <header>
//         <Navbar />
//         <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
//       </header>
//       <main>  
//         <Welcome /> 
//         <CTAComponent />
//       </main>
//     </section>
//   );
// }

/* <Discover /> */

/* {selectedPoolAddress && <PriceLineChart poolAddresses={selectedPoolAddress} />} */

// import React, { useState } from 'react';


// import Head from 'next/head';
// import Navbar from '../components/Navbar';
// import CTAComponent from '../components/CTAComponent';
// import Welcome from '../components/Welcome';
// import TokenGrid from '../components/TokenGrid';

// export default function Home() {
//   const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

//   return (
//     <section className="w-full bg-fondo-fondo min-h-screen bg-cover bg-center">
//       <Head>
//         <title>FlowFinance</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
// <header className="relative bg-center bg-no-repeat bg-cover h-screen">
//         <img
//           className="absolute inset-0 h-full w-full z-1"
//           src="/img/waves.png"
//           alt="Waves Background"
//         />        <Navbar />
//         <Welcome />
//         <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
//       </header>
//         <main>
//         <CTAComponent />
//       </main>
//     </section>
//   );
// }  

import React, { useState } from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import ContactUs from '../components/ContactUs';
import Welcome from '../components/Welcome';
import TokenGrid from '../components/TokenGrid';
import Discover from '../components/Discover';
import Footer from '../components/Footer';

export default function Home() {

  const [selectedPoolAddress, setSelectedPoolAddress] = useState(null);

   // Usar selectedPoolAddress en alguna parte de tu componente
  console.log(selectedPoolAddress);
  return (
    <div className="w-full  bg-gradient-to-t from-black to-gray-400 min-h-screen bg-cover bg-center absolute top-0 left-0 z-0">
      <Head>
        <title>FinanceFlow</title>
        <meta name="web3 Portal" content="Web3 utility Dapp" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* Otros componentes de tu aplicación */}
      <TokenGrid setSelectedPoolAddress={setSelectedPoolAddress} />
      <Welcome  />
      <Discover />
      <ContactUs />
      <Footer />
    </div>
  );
}

  
