import {
  AGENT_K9_MINT_ADDRESS,
  SOLANA_INCINERATOR_ADDRESS,
  SOLANA_INCINERATOR_URL,
} from "@/lib/levi/communityBurn";
import {
  AGENT_K9_DECIMALS,
  AGENT_K9_INITIAL_SUPPLY_RAW,
  AGENT_K9_SYMBOL,
} from "@/lib/agentK9/brand";

export {
  AGENT_K9_DECIMALS,
  AGENT_K9_INITIAL_SUPPLY_RAW,
  AGENT_K9_MINT_ADDRESS,
  AGENT_K9_SYMBOL,
  SOLANA_INCINERATOR_ADDRESS,
  SOLANA_INCINERATOR_URL,
};

export const BURN_TRACKER_COLLECTION = "agentK9BurnTracker";
export const BURN_TRACKER_DOCUMENT_ID = "agent-k9";
export const BURN_TRACKER_CACHE_TTL_MS = 2 * 60 * 60 * 1000;
export const BURN_TRACKER_REFRESH_LEASE_MS = 90 * 1000;
export const BURN_TRACKER_SIGNATURE_PAGE_SIZE = 12;
export const BURN_TRACKER_SOLSCAN_TRANSACTION_URL = "https://solscan.io/tx";
