import {
  SOLANA_INCINERATOR_ADDRESS,
  SOLANA_INCINERATOR_URL,
} from "@/lib/levi/communityBurn";
import {
  BULLISH_MULE_DECIMALS,
  BULLISH_MULE_INITIAL_SUPPLY_RAW,
  BULLISH_MULE_MINT_ADDRESS,
  BULLISH_MULE_SYMBOL,
} from "@/lib/bullishMule/brand";

export {
  BULLISH_MULE_DECIMALS,
  BULLISH_MULE_INITIAL_SUPPLY_RAW,
  BULLISH_MULE_MINT_ADDRESS,
  BULLISH_MULE_SYMBOL,
  SOLANA_INCINERATOR_ADDRESS,
  SOLANA_INCINERATOR_URL,
};

export const BURN_TRACKER_COLLECTION = "bullishMuleBurnTracker";
export const BURN_TRACKER_DOCUMENT_ID = "bullish-mule";
export const BURN_TRACKER_CACHE_TTL_MS = 2 * 60 * 60 * 1000;
export const BURN_TRACKER_REFRESH_LEASE_MS = 90 * 1000;
export const BURN_TRACKER_SIGNATURE_PAGE_SIZE = 12;
export const BURN_TRACKER_SOLSCAN_TRANSACTION_URL = "https://solscan.io/tx";
